---
branches:
  only:
  - source
  except:
  - master
language: ruby
rvm:
- 1.9.3
- 1.9.2
before_script:
- git config user.name "Jaime Jesús Delgado Meraz (via Travis-CI)"
- git config user.email "j2deme@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="j2deme/j2deme.github.com"
  - secure: QrtOt+9556Sa4IRLP5vE+Ji54j712qfH7ZiX7QbmAb7tjnNIbZibwrdJ9ervdrUsnMDlSqVpxoN4/GKTwKmmwjakLfhjKV1/Sc5RRfajeQFBZgbcJgZIE1fWg+Mzw0vr+EdoC764tpro4iXdkEgQuy3p9gjECwzFTVwJsZ8PgAA=
