# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://j2deme.github.com
title: Jaime J. Delgado Meraz
subtitle: Profesor, Developer, Tesista, Padre de Familia y Superheroe.
author: Jaime Jesús Delgado Meraz
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d/%m/%Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
#http://feeds.feedburner.com/JaimeDelgadoMeraz
subscribe_email:
# http://feedburner.google.com/fb/a/mailverify?uri=JaimeDelgadoMeraz&amp;loc=es_ES
# RSS feeds can list your email address if you like
email: j2deme@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
#/:categories/:title/
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categorias
category_title_prefix: "Categoria &rArr; "
markdown: kramdown
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Leer m&aacute;s &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase
category_feeds: true
# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
#default_asides: [custom/asides/subscribe.html,asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 2
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: j2deme
twitter_tweet_count: 2
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: true
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: j2deme
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: jaimedelgadomeraz
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-39058698-1

# Facebook Like
facebook_like: true

#prose.io settings
prose:
  rooturl: "source"
  metadata:
    "source/_posts": |
      layout: post
      title: "Untitled"
      comments: true
      categories: [technical]
      published: true
